### PR TITLE
Feature/oed schema changes

### PR DESCRIPTION
**Pull request by johcarter**
These are the changes for the ODS v2.0.0 release candidate

OED
* Version 2.0.0
* Updated documentation (rst files, csv and excel, but not pdf)
* Updated piwind oed files

**Location** file
* Added CondTag varchar(20) field
* Removed CondNumber int field
* Added OEDVersion varchar(10) field

**Account** file
* Added CondTag varchar(20) field
* Changed data type of CondNumber from int to varchar(20)
* Added OEDVersion varchar(10) field

**ReinsInfo** file
* Added RiskLevel char(3) field (from ReinsScope file)
* Added OEDVersion varchar(10) field

**ReinsScope** file
* Removed RiskLevel char(3) field (moved to ReinsInfo file)
* Added OEDVersion varchar(10) field

ORD
* Version 2.0.0
* Report name changed from Period Average Loss Table (PALT) to Average Loss Table (ALT)
* Reindexing of EPCalc and EPType as follows;
* EPCalc
1 = Mean Damage Ratio
2 = Full Uncertainty
3 = Per Sample Mean
4 = Sample Mean
* EPType
1 = OEP
2 = OEP TVaR
3 = AEP
4 = AEP TVaR
* Dropped version from ORD spec filename

@MattDonovan82 please can you review for inconsistencies in field changes? I have not updated the OED spec pdf as I don't have the word version. The updated documentation can be found in the RSTs. If you feel it is required, please can you update the pdf accordingly?  Also is there a reason that the excel spec is repeated in separate csvs? It makes it harder to maintain the same info in two places so i wonder whether the csvs are necessary or could be removed? thanks

### CODE REVIEW

**Comment by aiste-kalinauskaite** [comment]
Are you planning to incorporate CondNumber change to nvarchar(20)?

**Comment by johcarter** [comment]
Yes @aiste-kalinauskaite

**Review by MattDonovan82 — APPROVED** [review]
This all looks good to me @johcarter. I will dig out the word doc and amend. Let's leave the separate .csvs in there until we discuss internally and then we can remove them later if necessary.

The ORD definitions in the 'master' branch also still look accurate when discussing EPcalc and EPType

https://github.com/OasisLMF/OpenDataStandards/blob/master/OpenResultsData/ORD_Definitions.md

Matt

**Comment by johcarter** [comment]
Thanks @MattDonovan82 . I am merging into develop. Would you like to add your changes to the word doc to develop?

**Comment by MattDonovan82** [comment]
yes, I will do that in the next few days. thanks.

**Pull request merged**
